DEBUG 2021-02-02 18:52:14.917 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-02 18:52:14.918 UTC: 	 Running on: Linux cmslpc176.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-02-02 18:52:14.918 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-02 18:52:14.919 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-02-02 18:52:14.933 UTC: 	 Will use CRAB configuration file crab_chi850GeV_Suu4TeV_cfg.py
DEBUG 2021-02-02 18:52:14.933 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-02 18:52:15.084 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-02 18:52:15.114 UTC: 	 Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab_projects/crab_diquark_4TeV_chi850GeV_0000' already exists 
Please change the requestName in the config file
ERROR 2021-02-02 18:52:15.114 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab_projects/crab_diquark_4TeV_chi850GeV_0000' already exists 
Please change the requestName in the config file
INFO 2021-02-02 18:52:15.234 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab.log
DEBUG 2021-02-02 19:08:53.814 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-02 19:08:53.814 UTC: 	 Running on: Linux cmslpc176.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-02-02 19:08:53.814 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-02 19:08:53.826 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-02-02 19:08:53.887 UTC: 	 Will use CRAB configuration file crab_chi850GeV_Suu4TeV_cfg.py
DEBUG 2021-02-02 19:08:53.887 UTC: 	 Loading CRAB configuration file.
ERROR 2021-02-02 19:08:54.213 UTC: 	 Error while loading CRAB configuration:
name 'c' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-02-02 19:08:54.213 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'c' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-02-02 19:08:54.267 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab.log
DEBUG 2021-02-03 14:04:30.279 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 14:04:30.279 UTC: 	 Running on: Linux cmslpc106.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-02-03 14:04:30.279 UTC: 	 Executing command: 'status'
DEBUG 2021-02-03 14:04:30.280 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2021-02-03 14:04:30.282 UTC: 	 Error: crab_projects/crab_diquark_4TeV_chi850GeV_0000 is not a valid CRAB project directory.
ERROR 2021-02-03 14:04:30.282 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_diquark_4TeV_chi850GeV_0000 is not a valid CRAB project directory.
INFO 2021-02-03 14:04:30.285 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab.log
DEBUG 2021-02-22 11:57:58.105 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-22 11:57:58.106 UTC: 	 Running on: Linux cmslpc165.fnal.gov 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 10 08:19:23 CST 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-02-22 11:57:58.106 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-22 11:57:58.106 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-02-22 11:57:58.109 UTC: 	 Will use CRAB configuration file crab_chi1TeV_Suu5TeV_clustAlg_cfg.py
DEBUG 2021-02-22 11:57:58.109 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-22 11:57:58.118 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-22 11:57:58.120 UTC: 	 Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab_projects/crab_Suu_clusteringAlgorithm_0000' already exists 
Please change the requestName in the config file
ERROR 2021-02-22 11:57:58.120 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab_projects/crab_Suu_clusteringAlgorithm_0000' already exists 
Please change the requestName in the config file
INFO 2021-02-22 11:57:58.123 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_2_15/src/crab.log
